[msg MSG_000_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9048 65535 0]Akihabara was lots of fun.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I think I wanna try going somewhere else[n]sometime.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Kasumi]]
[s][vp 8 0 0 1 3 0]Oh yeah? I know a bunch of great places[n]around Tokyo if you're up for more![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...It really sounds like Sojiro wants me to[n]go back to school.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Kasumi]]
[s][vp 8 0 0 30 3 0]He has his reasons. I mean, I got arrested and still[n]have to go to school, like it or not.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 9197 65535 0]But you've got that big main character energy![n]Social situations are a peace of cake for you![n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9148 65535 0]I figured I could split the difference and [n]start taking online classes! Primo education [n]beamed straight to home base~![n][f 1 3 65535][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mweheheh - genius, right?[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]That won't help you at all.[e]
[s][f 0 8 2 1 2217]That's a great first step![clr 27][e]

[msg MSG_031_0_0 [Kasumi]]
[s][vp 8 0 0 31 3 0]If you could get everything[n]you needed from online school,[n]why would anyone bother showing up in person?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 9028 65535 0]Critical hit to the heart, sheesh…[n]You're prolly right, though. Just studying by myself is [n]way different from actual school.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Kasumi]]
[s][vp 8 0 0 31 3 0]The key to a good performance is a good [n]warmup routine! Hehe, reminds me of how I had[n]that brain training program when I was younger.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9161 65535 0][coop 10 5 8]Right!? The one with the floating head guy![n]We've gotta compare brain ages sometime![n][f 1 3 65535][w][e]
[s][f 4 24 0 4 0 38 5 100][f 4 24 0 4 0 5 3 100][f 4 24 0 4 0 1 7 30][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Though… I dunno if Sojiro'd really consider [n]online classes as going to school.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]School...[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 9018 65535 0]Um, to be honest...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I really do wanna go back.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Do you think I'll be able to?[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s][f 0 8 2 1 2217]Absolutely![clr 27][e]
[s]If you put in the work.[e]
[s]Will you stick with it?[e]

[msg MSG_033_0_0 [Kasumi]]
[s][vp 8 0 0 33 3 0]You're bright, you're eager, and you bounce back quickly![n]That's... honestly more than can be said for a[n]lot of students.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Kasumi]]
[s][vp 8 0 0 34 3 0]Remember that we're not going to be in the same [n]class or anything - you'll have to be ready [n]to face up to things on your own.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Kasumi]]
[s][vp 8 0 0 35 3 0]I don't see why you wouldn't be able to go back - the [n]trickier part would be staying there and not[n]slipping back into your comfort zone.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9199 65535 0][coop 10 10 8]...Yeah![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9045 65535 0][coop 10 5 8]I know you can't always be behind me, but I need [n]your coaching for as long as I can, Kasumi![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 9038 65535 0]Huh. I didn't think about it that way.[n]So it's more an endurance[n]grind than a speedrun…[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'm gonna do my best![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Futaba]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 8 14 300 1][vp 8 2 0 9157 65535 0]Oh, I should make a promise list![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]My mom used to have me do that[n]all the time.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]She'd write all my goals for the month,[n]like cleaning the house or running[n]errands for her.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Then when I'd finish one, she'd mark it off[n]with a big stamp.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][cut 1 65535 65535 65535 65535 65535 65535 65535 8 1 300 65535][vp 8 0 0 0 65535 0]She always used to write comments too...[n]Those were the best.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, and once I finished all my goals,[n]she would take a day off work to spend[n]time with me.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Kasumi]]
[s][vp 8 0 0 36 3 0]There's something about ticking off a checklist [n]that really fires you up![n][f 1 3 65535][w][e]
[s][vp 8 0 0 42 3 0]When we were little, Sumire and I would always work[n]together to fill out our chore chart so Mom would[n]let us play that dancing arcade game.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Futaba]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 8 1 300 1][vp 8 2 0 9196 65535 0]It's decided then! I'm gonna make[n]a promise list![n][f 1 3 65535][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Time to get my ideas ready![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9089 65535 0]...All done![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]So, these are my promises.[n][f 1 3 65535][w][e]

[msg MSG_019_5_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]1. Go somewhere with lots of people.[n]Getting used to big crowds is key.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]2. Go to school. I wanna see what[n]the inside of a normal high school[n]looks like.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]3. Learn about my generation.[n]I definitely need more info...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]4. Have a normal conversation with[n]a stranger my age.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 9098 65535 0]...How's that?[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Kasumi]]
[s][vp 8 0 0 37 3 0]Hmm... Starts out simple, then gets tougher as you go on…[n]it's not dissimilar from planning a [n]gymnastics routine, actually.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 43 3 0]I guess you're not the only one slipping into old habits.[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]Sounds good to me.[e]
[s]Can you tell me again?[e]

[msg MSG_021_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]If you want...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9151 65535 0]I wanna try and finish all of these someday, Coach![n]I'll work even harder with my navigation in return![n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You're gonna have to help me though. I'll work [n] even harder with my navigation in return![n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]I can sense Futaba's trust in me...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 9018 65535 0]S-So, um...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][cut 1 65535 65535 65535 65535 65535 65535 65535 8 12 300 65535][vp 8 0 0 0 65535 0]If I finish all the promises, do you think[n]I could have a reward?[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I know it's kinda weird to ask... but[n]having a reward waiting at the finish[n]line will totally push me onward![n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Kasumi]]
[s][vp 8 0 0 38 3 0]Sure, I don't see why not.[n]I'll have to think of something, though.[n]Gimme me some time, okay?[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Futaba]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 8 12 300 1][vp 8 2 0 9196 65535 0]No way, you mean it? Okay okay, I got this![n][f 1 3 65535][w][e]
[s][bup 0 8 0 65535 0][vp 1 0 0 0 0 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Though I'm kinda exhausted from[n]making the list, soooooo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tomorrow. I got this... tomorrow.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Futaba]]
[s][vp 8 2 0 9012 65535 0]Welp, I'm gonna make like a hedgehog[n]and roll outta here![n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Kasumi]]
[s][vp 8 0 0 39 3 0]"Ring" me if you need me![n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 8 0 0 0 65535 0]Futaba went home...[n][f 1 3 65535][w][e]

